# These are supported funding model platforms

github: notadamking
patreon: notadamking
custom: ['https://gitcoin.co/grants/155/tensortrade-trade-efficiently-with-reinforcement-l', 'https://www.blockchain.com/btc/address/1Lc47bhYvdyKGk1qN8oBHdYQTkbFLL3PFw']
